Keep green
fusionjs/probot-app-workflow pull request #134
Opened 2019-01-26 00:25 UTC by chrisdothtml

2019-01-26 00:30 UTC, chrisdothtml commented
@KevinGrandon failed CI looks like same issue as other repo?

2019-01-26 01:20 UTC, KevinGrandon commented
Yeah looks like we need to update the base image in the Dockerfile here.

2019-01-28 19:28 UTC, KevinGrandon requested changes

2019-01-28 19:28 UTC, KevinGrandon commented on Dockerfile
> +ENV YARN_VERSION 1.13.0
Hmm, seems like this is not installing the proper yarn version? Maybe we can use the uber-web base image instead of node?

2019-01-28 19:47 UTC, chrisdothtml commented on Dockerfile
> +ENV YARN_VERSION 1.13.0
Yeah, would also require changing the hard-coded node version in this package so wanted to try this first. Will switch it to our base image again

2019-01-28 21:34 UTC, KevinGrandon approved these changes

2019-01-28 21:35 UTC, chrisdothtml commented
!merge

2019-01-28 21:35 UTC, merged